name: Publish Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install jq (for version extraction)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run type-check

      - name: Build package
        run: bun run build

      - name: Bump version (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          bun run bump:${{ github.event.inputs.version }}
          NEW_VERSION=$(jq -r .version package.json)
          echo "New version: $NEW_VERSION"
          git add package.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: bump version to $NEW_VERSION"
            git tag v$NEW_VERSION
            git push origin master
            git push origin v$NEW_VERSION
          else
            echo "No changes to commit."
          fi

      - name: Set up npm authentication
        run: |
          echo "registry=https://registry.npmjs.org/" > $HOME/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc

      - name: Show Bun user (debug)
        run: bun whoami

      - name: Publish to npm
        run: bun run bun:publish:npm

      - name: Set up GitHub Packages authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> $HOME/.npmrc

      - name: Publish to GitHub Packages
        run: bun run bun:publish:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack DXT manifest
        run: bun run dxt:pack

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          gh release create v$CURRENT_VERSION raindrop-mcp.dxt --title "Release v$CURRENT_VERSION" --notes "DXT manifest for MCP"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
