name: Publish Package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the project
      - name: Build the project
        run: bun run build

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}